In [7]:
import numpy as np


 ## Slicing

In [4]:
arr = np.array([10,203,4943,3])

In [6]:
print(arr[1:4]) #slice from index 1 to 3

[ 203 4943    3]


In [8]:
print(arr[:3]) #first three element

[  10  203 4943]


In [10]:
print(arr[::2]) #print every second element

[  10 4943]


## Slicing returns a view, not copy! changes affect the original array

In [41]:
a2 = arr[:2]
#to overcome this issue use arr[:2].copy
a2

array([   10, 55500])

In [37]:
a2[1] =54500
a2

array([   10, 54500])

In [39]:
arr

array([   10, 55500,  4943,     3])

## Fancy Indexing

In [48]:
arr = np.array([10,20,30,40,50])
idx = [0,2,4]
print(arr[idx])

[10 30 50]


## Boolaen Masking(Filter Data)

In [53]:
mask = arr > 30
arr[mask]

array([40, 50])

# Task

'''
Create a 3×3 array filled with random numbers and print its shape.
Convert an array of floats [1.1, 2.2, 3.3] into integers.
Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
Reshape a 1D array of size 9 into a 3×3 matrix.
Use boolean masking to filter numbers greater than 50 in an array.
'''

In [38]:
arr = np.eye(3)

In [40]:
arr


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
arr.shape

(3, 3)

In [44]:
na = arr.astype('float64')
na

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
index = [2]
print(na[index][0][2])

1.0


In [54]:
newarr = np.array([1,2,3,4,5,6,7,8,9])

In [56]:
newarr.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
n2 = newarr > 5
newarr[n2]

array([6, 7, 8, 9])