## DataType in NumPy

In [2]:
import numpy as np

In [4]:
arr  = np.array([234,5,353,5])
arr.dtype # can be differnt on mac & windows

dtype('int32')

In [6]:
arr

array([234,   5, 353,   5])

In [8]:
arr.astype('float64')

array([234.,   5., 353.,   5.])

In [12]:
arr2  = np.array([234,5,353,5],dtype="float64")

## Downcasting to save memory 

In [15]:
arr.nbytes

16

In [17]:
arr2.nbytes

32

In [19]:
arr_int64 = np.array([1,2,3],dtype=np.int64)
arr_int32 = np.array([1,2,3],dtype=np.int32)

print(arr_int64.nbytes) #8 bytes * 3 element

24


In [23]:
print(arr_int32.nbytes) # 4 bytes * 3 element

12


### Mainly NumPy Designed for Numerically operatin, try to avoid to use string datatype

In [26]:
arr = np.array(['a','b','c'],dtype='U10')

 ## Complex Numbers

In [31]:
arr = np.array([1+2j,3+4j,5+6j],dtype='complex128') #can use 64
arr

array([1.+2.j, 3.+4.j, 5.+6.j])

## can be stored dict or object, but not good idea

In [36]:
arr = np.array([{'a':1},[1,2,3],'hello'],dtype=object)
arr

array([{'a': 1}, list([1, 2, 3]), 'hello'], dtype=object)