In [1]:
import numpy as np


In [ ]:
arr1 = np.array([[1,2,3],[4,1,8]])

In [7]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.zeros((3,4)) #4 column 3 row

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
#Creating arrays from scrath

In [25]:
np.ones((2,4)) #2x4 arrays of ones


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.full((4,2),7) # 2x2 array filled with 7

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

In [31]:
np.eye(5) #identty matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
np.arange(1,100,9) # 1 to 100 there 2 skip
#100: explicit
#1 , 1+9 = 10, 10+9=19,...,91

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [47]:
np.linspace(0,1,6) #print 0 to 1 b/w 6 equaly space,entry

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [49]:
myarr = np.array([[1,2,3],[4,5,6],[43,52,5],[245,3,2]])

In [51]:
myarr


array([[  1,   2,   3],
       [  4,   5,   6],
       [ 43,  52,   5],
       [245,   3,   2]])

In [53]:
myarr.shape


(4, 3)

In [55]:
myarr.size

12

In [57]:
myarr.ndim

2

In [59]:
myarr.dtype

dtype('int32')

## Changing data type

In [62]:
#numpy in not allow one element int and another is float
# must all equal

In [66]:
myarr = np.array([[1,2,3],[4,5,6],[43,52,5],[245,3,2],[543,2,2]],dtype='float32')

In [68]:
myarr


array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [ 43.,  52.,   5.],
       [245.,   3.,   2.],
       [543.,   2.,   2.]], dtype=float32)

In [76]:
n=myarr.astype('float64')

In [78]:
n.dtype


dtype('float64')

In [82]:
myarr.dtype

dtype('float32')

In [84]:
myarr = np.array([[1,2,3],[4,5,6],[43,52,5],[245,3,2]])

In [86]:
myarr.shape

(4, 3)

In [92]:
reshaped = myarr.reshape((3,4)) #3 row , 4 columns

In [90]:
reshaped

array([[  1,   2,   3,   4],
       [  5,   6,  43,  52],
       [  5, 245,   3,   2]])

In [94]:
myarr

array([[  1,   2,   3],
       [  4,   5,   6],
       [ 43,  52,   5],
       [245,   3,   2]])

In [96]:
#myarr.reshape((4,5)) # not possible bcoz total array element is 12