In [1]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr[0] #-> first row

array([1, 2, 3])

## Indexing

In [7]:
arr[1]

array([4, 5, 6])

In [9]:
arr[2]

array([7, 8, 9])

In [11]:
#arr[row][column]

In [13]:
arr[2][2]

9

## Sum of 2D

In [17]:
np.sum(arr,axis=0) #axis 0 -> row

array([12, 15, 18])

In [21]:
np.sum(arr,axis =1 )#axis 1-> column

array([ 6, 15, 24])

## New Indexing on 2D

In [26]:
arr[0,1] # 0-> row, 1> column

2

In [30]:
arr[0:2,1:] #0:2 -> 0 & 1 index vali row on that
# and column in 1 & 2 column  

array([[2, 3],
       [5, 6]])

## Indexing in 3D Arrays

In [152]:
arr3D = np.array([
    [[1, 2, 3], [4, 5, 6]],
    
    [[7, 8, 9], [10, 11, 12]]
])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

(2, 2, 3)


In [84]:
arr3D


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [78]:
arr3D.shape #(depth,rows, column)

(3, 3)

## Accessing Element in 3D

In [86]:
#(first sheet,second row,third column)
print(arr3D[0,1,2])

6


In [98]:
print(arr3D[0,1,2])

6


In [118]:
print(arr3D[:,0,:]) #:->> consider all 2D array, 0-> un 2D array ki first row, :-> unke sare column

[[1 2 3]
 [7 8 9]]


## Practice Example: Selectin Data along axes

In [131]:
#get all rows of the first column

first_col = arr[:,0] #sari rows of first cloumn
first_col

array([1, 4, 7])

In [135]:
#Get the first row from each "Sheet" in a 3D array

In [137]:
first_rows = arr3D[:,0,:]

In [139]:
first_rows

array([[1, 2, 3],
       [7, 8, 9]])

## Changing Data Along an Axis

In [142]:
#Replace all elements in column 1 with 0
arr[:,1] = 0
arr

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])

In [154]:
arr3D[:,1,:] = 0
arr3D

array([[[1, 2, 3],
        [0, 0, 0]],

       [[7, 8, 9],
        [0, 0, 0]]])