In [1]:
import numpy as np

In [35]:
arr = np.array([3,50,2,34,3,3,30,33])

In [5]:
np.mean(arr)

10.75

In [7]:
np.min(arr)

2

In [9]:
np.max(arr)

33

In [11]:
np.std(arr)

12.891373084353738

In [13]:
np.var(arr)


166.1875

In [15]:
np.sum(arr)

43

In [17]:
np.prod(arr)

990

In [21]:
np.percentile(arr,50)

4.0

In [25]:
np.argmin(arr) #return index of min value

2

In [27]:
np.argmax(arr)

3

In [29]:
np.corrcoef(arr)

1.0

In [37]:
np.unique(arr)

array([ 2,  3,  5, 33, 34])

In [43]:
np.cumsum(arr) # cumulative sum

array([ 3,  8, 10, 44, 47, 50, 53, 86])

In [45]:
np.log(arr)

array([1.09861229, 1.60943791, 0.69314718, 3.52636052, 1.09861229,
       1.09861229, 1.09861229, 3.49650756])