In [1]:
### Vectorization is when NumPy applies operations to multiple array
### elemenets simultaneouly using efficient CPU instructions, bypassing slow python loops.

In [3]:
### Broadcasting is when NumPy automcatilly expands arrays of differnt shapes to make them compatible for 
### element-wise operation without actully replicating data in memory.
### BroadCasting: scaling arrays without extra memory

In [5]:
import numpy as np


In [7]:
arr = np.array([1,2,3,4,5])

In [9]:
result = arr ** 2

In [11]:
result

array([ 1,  4,  9, 16, 25])

In [13]:
result = arr + 10 #broadcasting
result

array([11, 12, 13, 14, 15])

In [ ]:
## Here the scaler 10 is "broadcast" across the entire array,
## and no extra memoery is used.

## BroadCasting in 2D array

In [26]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([1,2,3])
result = arr1 + arr2
result

array([[2, 4, 6],
       [5, 7, 9]])

 ## Ex: Normalizing Data Using BroadCasting

In [34]:
data = np.array([[10,20,30],
                [40,50,60],
                [70,80,90],
                [43,5,23]])

In [38]:
mean = data.mean(axis=0)
std = data.std(axis=0)
#calculating mean and SD deviation for each feature column

In [44]:
normalized_data = (data-mean)/std
#Normalizing the data using broadcasting

In [42]:
normalized_data

array([[-1.44685858, -0.65094455, -0.78055659],
       [-0.03528923,  0.39056673,  0.34795896],
       [ 1.37628011,  1.43207802,  1.47647452],
       [ 0.1058677 , -1.1717002 , -1.04387689]])